apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-mongodb
  namespace: chat-app
spec:  
  replicas: 1
  selector:
    matchLabels:
      app: chat-mongodb
  template:                         # ✅ moved here, under spec (not selector)
    metadata:
      name: mongodb-pod
      labels:
        app: chat-mongodb
    spec:
      containers:
      - name: chat-mongodb
        image: mongo:latest
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: "mongoadmin"
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: "secret"
        volumeMounts:
        - name: mongodb-data
          mountPath: /data/db
      volumes:
      - name: mongodb-data
        persistentVolumeClaim:
          claimName: mongodb-pvc
